name: Continuous Integration Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'apps/**'
      - 'libs/**'

  push:
    branches:
      - main
    paths:
      - 'apps/**'
      - 'libs/**'

jobs:
  test:
    name: 'Run unit tests'
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: 'Checkout repository'
      - name: 'Install PNPM'
        run: npm install -g pnpm
      - name: 'Install Dependencies'
        run: pnpm install
      - name: 'Run Tests'
        run: npx nx run test
  lint:
    name: 'Run linter'
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g pnpm
      - run: pnpm install
      - name: 'Run Linter'
        run: npx nx run lint
