name: Continuous Integration Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - 'apps/**'
      - 'libs/**'

  push:
    branches:
      - main
    paths:
      - 'apps/**'
      - 'libs/**'

jobs:
  test:
    name: 'Run unit tests'
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: 'Checkout repository'
      - name: 'Install PNPM'
        run: npm install -g pnpm
      - name: 'Install Dependencies'
        run: pnpm install
      - name: 'Run Tests'
        run: npx nx run test
